/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_temperature_measurement        21
#define gattdb_BP_Measurement                 25
#define gattdb_HR_measurement                 29
#define gattdb_SPO2                           33
#define gattdb_read_time_sec                  37
#define gattdb_ota_control                    41


#endif // __GATT_DB_H
